### ISSUE TITLE
Can I compile the project with C ++ 11?

### ISSUE THREAD

**Issue by sanshanxiashi** [tmplt/fuzzywuzzy#15]
I failed to compile with C ++ 11. What is the GCC version requirement?

**Comment by tmplt** [comment]
Been a while since I worked with this library. @kketernality, @backdround?

**Comment by tmplt** [comment]
Any compiler supporting C++14 should suffice.

**Comment by kketernality** [comment]
@sanshanxiashi Any error message to show from compiler?
